version: '3'
services:
  iiaclaw-web:
    image: biz/iiaclaw-web:0.2.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8501
    env_file:
      - .env
    volumes:
      - ./.logs:/app/.logs

      